config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lunches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lunch.rb
class Lunch < ApplicationRecord
end

app/models/slack_settings.rb
class SlackSettings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  # GET /lunches
  # GET /lunches.json
  def index
    @lunches = Lunch.all
  end

  # GET /lunches/1
  # GET /lunches/1.json
  def show
  end

  # GET /lunches/new
  def new
    @lunch = Lunch.new
  end

  # GET /lunches/1/edit
  def edit
  end

  # POST /lunches
  # POST /lunches.json
  def create
    @lunch = Lunch.new(lunch_params)
    respond_to do |format|
      if @lunch.save
        @lunches = Lunch.all
        format.html { redirect_to lunches_url, notice: 'Lunch was successfully updated.' }
        format.json { render @lunch, status: :ok }
      else
        format.html { render :new }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lunches/1
  # PATCH/PUT /lunches/1.json
  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        @lunches = Lunch.all
        format.html { redirect_to lunches_url, notice: 'Lunch was successfully updated.' }
        format.json { render @lunch, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lunches/1
  # DELETE /lunches/1.json
  def destroy
    @lunch.destroy
    @lunches = Lunch.all
    respond_to do |format|
      format.html { redirect_to lunches_url, notice: 'Lunch was successfully destroyed.' }
      format.json { render @lunch, status: :ok, location: @lunches }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lunch_params
      params.require(:lunch).permit(:name, :location, :phone, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lunches_helper.rb
module LunchesHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Slunch
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    css:
      .container {
        width: 720px;
        margin: auto;
        align-items: center;
      }
      h1 {
        text-align: center;
      }
  body
    .container
      = yield

app/views/lunches/_form.html.erb
<%= form_for(@lunch) do |f| %>
  <% if @lunch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lunch.errors.count, "error") %> prohibited this lunch from being saved:</h2>

      <ul>
      <% @lunch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lunches/_form.slim
.panel.panel-default
  .panel-body
    = form_for(@lunch) do |f|
      - if @lunch.errors.any?
        #error_explanation
          h2
            = pluralize(@lunch.errors.count, "error")
            | prohibited this lunch from being saved:
          ul
            - @lunch.errors.full_messages.each do |message|
              li= message
      .field
        = f.label :name
        br/
        = f.text_field :name, class: 'form-control'
      .field
        = f.label :location
        br/
        = f.text_field :location, class: 'form-control'
      .field
        = f.label :phone
        br/
        = f.text_field :phone, class: 'form-control'  
      .field
        = f.label :description
        br/
        = f.text_area :description, class: 'form-control' 
        br/
      .actions
        = f.submit class: 'btn btn-primary pull-right'

app/views/lunches/edit.html.erb
<h1>Editing Lunch</h1>

<%= render 'form' %>

<%= link_to 'Show', @lunch %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/edit.slim
h2.text-center Editing Lunch
= render 'form'
= link_to 'Back', lunches_path, class: "pull-right"

app/views/lunches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lunches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Phone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lunches.each do |lunch| %>
      <tr>
        <td><%= lunch.name %></td>
        <td><%= lunch.location %></td>
        <td><%= lunch.phone %></td>
        <td><%= lunch.description %></td>
        <td><%= link_to 'Show', lunch %></td>
        <td><%= link_to 'Edit', edit_lunch_path(lunch) %></td>
        <td><%= link_to 'Destroy', lunch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lunch', new_lunch_path %>

app/views/lunches/index.slim
h1 Lunch List
- flash.each do |name, msg|
  = content_tag :div, msg, class: "alert alert-success"
table.table.table-striped.table-hover
  thead
    tr
      th 餐廳
      th 地點
      th 電話
      th 敘述
      th colspan="1" 
  tbody
    - @lunches.each do |lunch|
      tr
        td= lunch.name
        td= lunch.location
        td= lunch.phone
        td= lunch.description
        td
          = link_to edit_lunch_path(lunch)
            span.glyphicon.glyphicon-edit
        td
          = link_to lunch, method: :delete, data: {confirm: 'Are you sure?'} 
            span.glyphicon.glyphicon-remove

= link_to 'New Lunch', new_lunch_path, class:'btn btn-danger pull-right'

app/views/lunches/new.html.erb
<h1>New Lunch</h1>

<%= render 'form' %>

<%= link_to 'Back', lunches_path %>

app/views/lunches/new.slim
h1 New Lunch
= render 'form'
= link_to 'Back', lunches_path, class: "pull-right"

app/views/lunches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lunch.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @lunch.location %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lunch.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lunch.description %>
</p>

<%= link_to 'Edit', edit_lunch_path(@lunch) %> |
<%= link_to 'Back', lunches_path %>

app/views/lunches/show.slim
br
br
.panel.panel-default
  .panel-body
    p#notice= notice
    p
      strong Name:
      = @lunch.name
    p
      strong Location:
      = @lunch.location
    = link_to edit_lunch_path(@lunch)
      span.glyphicon.glyphicon-edit
    = link_to lunches_path
      span.glyphicon.glyphicon-eye-open